version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    dns:
      - 8.8.8.8
      - 1.1.1.1

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8000:8000"