name: Deploy to OCI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd ${{ secrets.OCI_DIRECTORY }}
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
            echo "Despliegue completado con éxito 🚀"
